[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-poly = "0.5.0"
ark-ff = "0.5.0"
ark-bls12-381 = "0.5"
ark-std = "0.5"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "2.0.12"
ark-serialize = { version = "0.5", features = ["derive"] }