[package]
name = "stoffelmpc-mpc"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
tracing-subscriber.workspace = true
stoffelmpc-network = { path = "../network/"}
ark-ff.workspace = true
serde.workspace = true
ark-serialize.workspace = true
tokio.workspace = true
tracing.workspace = true
ark-poly.workspace = true
ark-std.workspace = true
ark-bls12-381.workspace = true
bincode.workspace = true
threshold_crypto.workspace = true
async-trait.workspace = true
sha2.workspace = true
rs_merkle.workspace = true
reed-solomon-erasure.workspace = true
rand.workspace = true
futures.workspace = true

[dev-dependencies]
once_cell = "1.21.3"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
