[package]
name = "stoffelmpc-mpc"
version.workspace = true
edition.workspace = true

[dependencies]
tracing-subscriber.workspace = true
stoffelmpc-common = { path = "../common" }
ark-ff.workspace = true
