//! A generic GF(2^K) field, parameterized entirely by const generics: the field's degree `K`,
//! its reduction polynomial `MODULUS` (as a `(K+1)`-bit value with bit `K` set — e.g. for
//! `K = 8`, `x^8 + x^4 + x^3 + x + 1` is `0b1_0001_1011 = 0x11B`), and a multiplicative
//! `GENERATOR` for that field.
//!
//! This is a separate, more general mechanism from [`super::field::Gf256`] — `Gf256` stays as
//! the hand-tuned, `u8`-backed, wire-efficient GF(2^8) implementation it already was (nothing
//! about it changes here). `Gf2k<K, MODULUS, GENERATOR>` trades that wire efficiency (it's
//! always backed by a `u128`, regardless of `K`, so a `Gf2k<8, ..>` costs 16x what `Gf256` does
//! on the wire) for the ability to stand up a *different* field size without hand-writing a new
//! concrete type and its own bit-width-specific reduction loop each time.
//!
//! # Three ready-made sizes, and how to add your own
//!
//! [`Gf2p4`], [`Gf2p8`], [`Gf2p16`] below are curated, verified starting points. The type itself
//! isn't limited to them — `Gf2k<K, MODULUS, GENERATOR>` accepts any `K`/`MODULUS`/`GENERATOR`
//! you supply, so a `K` not in this list is a type alias away, not a blocker:
//!
//! ```ignore
//! // 1. Source a MODULUS (irreducible polynomial of degree K over GF(2)) and a GENERATOR
//! //    (primitive element) for your K — e.g. from a published table of irreducible
//! //    polynomials, or your own derivation.
//! // 2. Declare the type:
//! type Gf2p32 = Gf2k<32, 0x0000_0000_04C1_1DB7, 0x2>; // <- illustrative, not verified
//! // 3. Verify it before relying on it — same check this module runs on Gf2p4/Gf2p8/Gf2p16:
//! #[test]
//! fn test_gf2p32_is_valid() {
//!     assert!(verify_field_and_generator::<Gf2p32>());
//! }
//! ```
//!
//! Getting `MODULUS` or `GENERATOR` wrong is silent and structural, not caught by the type
//! system: a reducible "modulus" isn't actually a field (some nonzero elements won't be
//! invertible), and a non-primitive "generator"'s powers cycle before covering all `2^K - 1`
//! nonzero elements. [`verify_field_and_generator`] checks both, exhaustively, for any
//! `F: BinaryField` — run it on any new instantiation before trusting it.
//!
//! # Limits
//!
//! Backed by `u128`, so `MODULUS` (which needs bit `K` set) only fits for `K <= 127`. In
//! practice, domain sizes anywhere near that are never useful (`2^127` parties), so this isn't a
//! real-world constraint. [`verify_field_and_generator`] is exhaustive (`O(2^K)`), so it's only
//! practical to run directly for smaller `K` (comfortably up to `K ~ 20`); for larger `K`,
//! confirming irreducibility/primitivity needs the algebraic tests those properties are defined
//! by (polynomial irreducibility testing, factoring `2^K - 1` for the primitivity check) rather
//! than brute force — not provided by this module.

use ark_std::rand::Rng;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::ops::{Add, Mul, Sub};

use super::field::BinaryField;

/// An element of GF(2^K), reduced modulo `MODULUS`, with multiplicative structure generated by
/// `GENERATOR`. See the module docs for what `MODULUS`/`GENERATOR` must satisfy, and
/// [`verify_field_and_generator`] to check a candidate pair.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Gf2k<const K: usize, const MODULUS: u128, const GENERATOR: u128>(u128);

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> fmt::Debug
    for Gf2k<K, MODULUS, GENERATOR>
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Gf2k<{K}>({:#x})", self.0)
    }
}

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> Gf2k<K, MODULUS, GENERATOR> {
    /// `2^K - 1`, saturating at `usize::MAX` for `K` at or beyond the platform's `usize` width
    /// (a purely defensive cap — no real domain approaches that size).
    const MAX_DOMAIN_SIZE: usize = {
        if K >= usize::BITS as usize {
            usize::MAX
        } else {
            (1usize << K) - 1
        }
    };

    pub fn new(value: u128) -> Self {
        Gf2k(value & Self::mask())
    }

    const fn mask() -> u128 {
        if K >= 128 {
            u128::MAX
        } else {
            (1u128 << K) - 1
        }
    }
}

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> Add
    for Gf2k<K, MODULUS, GENERATOR>
{
    type Output = Self;
    /// Addition in GF(2^K) is XOR — not a typo for `|`/`&`, hence the lint suppression below.
    #[allow(clippy::suspicious_arithmetic_impl)]
    fn add(self, other: Self) -> Self {
        Gf2k(self.0 ^ other.0)
    }
}

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> Sub
    for Gf2k<K, MODULUS, GENERATOR>
{
    type Output = Self;
    /// Subtraction == addition in characteristic 2 — not a typo for a real subtraction.
    #[allow(clippy::suspicious_arithmetic_impl)]
    fn sub(self, other: Self) -> Self {
        self + other
    }
}

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> Mul
    for Gf2k<K, MODULUS, GENERATOR>
{
    type Output = Self;
    /// Carry-less polynomial multiply, reduced against `MODULUS` one bit at a time — the same
    /// shift-and-reduce shape as `Gf256::mul`, generalized from fixed 8-/9-bit widths to `K`/
    /// `K+1`-bit widths via the const generics.
    fn mul(self, other: Self) -> Self {
        let mut result: u128 = 0;
        let mut a = self.0;
        let mut b = other.0;

        while b != 0 {
            if b & 1 != 0 {
                result ^= a;
            }
            a <<= 1;
            if (a >> K) & 1 != 0 {
                a ^= MODULUS;
            }
            b >>= 1;
        }

        Gf2k(result)
    }
}

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> BinaryField
    for Gf2k<K, MODULUS, GENERATOR>
{
    const MAX_DOMAIN_SIZE: usize = Self::MAX_DOMAIN_SIZE;

    fn zero() -> Self {
        Gf2k(0)
    }

    fn one() -> Self {
        Gf2k(1)
    }

    fn is_zero(&self) -> bool {
        self.0 == 0
    }

    fn generator() -> Self {
        Gf2k::new(GENERATOR)
    }

    /// Multiplicative inverse via Fermat: `a^-1 = a^(2^K - 2)`.
    fn inverse(&self) -> Option<Self> {
        if self.0 == 0 {
            None
        } else {
            let exponent = (1u128 << K) - 2;
            Some(self.pow_u128(exponent))
        }
    }

    /// `BinaryField::pow` takes a `u64` exponent, too narrow for `K > 64`'s Fermat exponent
    /// `2^K - 2`; `inverse` uses [`Self::pow_u128`] directly instead. This impl is kept for
    /// trait conformance and works correctly for any exponent that fits `u64`.
    fn pow(&self, exp: u64) -> Self {
        self.pow_u128(exp as u128)
    }

    fn random(rng: &mut impl Rng) -> Self {
        Gf2k::new(rng.gen::<u128>())
    }
}

impl<const K: usize, const MODULUS: u128, const GENERATOR: u128> Gf2k<K, MODULUS, GENERATOR> {
    fn pow_u128(&self, mut exp: u128) -> Self {
        let mut result = Gf2k::<K, MODULUS, GENERATOR>::one();
        let mut base = *self;

        while exp > 0 {
            if exp & 1 == 1 {
                result = result * base;
            }
            base = base * base;
            exp >>= 1;
        }

        result
    }
}

/// Exhaustively verifies that `F::generator()`'s powers visit every nonzero element of `F`
/// exactly once before returning to `F::one()` — equivalent to confirming `MODULUS` is
/// irreducible (every nonzero element is invertible, checked along the way) and `GENERATOR` is
/// primitive (order exactly `F::MAX_DOMAIN_SIZE`, not a proper divisor of it). `O(F::MAX_DOMAIN_SIZE)`,
/// so only practical for smaller fields — see the module docs' Limits section.
pub fn verify_field_and_generator<F: BinaryField>() -> bool {
    let order = F::MAX_DOMAIN_SIZE;
    let mut x = F::one();
    let mut seen = std::collections::HashSet::new();

    for _ in 0..order {
        if x.is_zero() || !seen.insert(format!("{x:?}")) {
            return false;
        }
        match x.inverse() {
            Some(inv) if inv * x == F::one() => {}
            _ => return false,
        }
        x = x * F::generator();
    }
    x == F::one()
}

/// GF(2^4), reduction polynomial `x^4 + x + 1`. Verified below: `verify_field_and_generator`
/// confirms exhaustively over all 16 elements.
pub type Gf2p4 = Gf2k<4, 0x13, 0x02>;

/// GF(2^8), the exact same reduction polynomial and generator as [`super::field::Gf256`]
/// (AES's `x^8 + x^4 + x^3 + x + 1`) — included primarily as a cross-validation that the generic
/// machinery agrees with the hand-tuned implementation, not because you'd prefer this over
/// `Gf256` for actual GF(2^8) use (it's 16x larger on the wire for the same field).
pub type Gf2p8 = Gf2k<8, 0x11B, 0x03>;

/// GF(2^16), reduction polynomial `x^16 + x^12 + x^3 + x + 1`. Verified below:
/// `verify_field_and_generator` confirms exhaustively over all 65536 elements.
pub type Gf2p16 = Gf2k<16, 0x1100B, 0x02>;

#[cfg(test)]
mod tests {
    use super::super::field::Gf256;
    use super::*;
    use ark_std::test_rng;

    #[test]
    fn test_gf2p4_field_and_generator_valid() {
        assert!(verify_field_and_generator::<Gf2p4>());
    }

    #[test]
    fn test_gf2p8_field_and_generator_valid() {
        assert!(verify_field_and_generator::<Gf2p8>());
    }

    #[test]
    fn test_gf2p16_field_and_generator_valid() {
        assert!(verify_field_and_generator::<Gf2p16>());
    }

    #[test]
    fn test_gf2p8_matches_gf256() {
        // Cross-validation: Gf2p8 (generic machinery) and Gf256 (hand-tuned) must compute
        // identically, element for element, since they share the same modulus and generator.
        for a in 0u8..=255 {
            for b in 0u8..=255 {
                let (ga, gb) = (Gf256(a), Gf256(b));
                let (pa, pb) = (Gf2p8::new(a as u128), Gf2p8::new(b as u128));

                assert_eq!((ga + gb).0 as u128, (pa + pb).0, "add mismatch at ({a},{b})");
                assert_eq!((ga * gb).0 as u128, (pa * pb).0, "mul mismatch at ({a},{b})");
            }
        }
    }

    #[test]
    fn test_gf2k_arithmetic_and_serde_roundtrip() {
        let mut rng = test_rng();
        for _ in 0..200 {
            let a = Gf2p16::random(&mut rng);
            let b = Gf2p16::random(&mut rng);
            let c = Gf2p16::random(&mut rng);

            assert_eq!(a + b, b + a);
            assert_eq!(a * b, b * a);
            assert_eq!((a + b) + c, a + (b + c));
            assert_eq!((a * b) * c, a * (b * c));
            assert_eq!(a * (b + c), a * b + a * c);

            let bytes = bincode::serialize(&a).unwrap();
            let back: Gf2p16 = bincode::deserialize(&bytes).unwrap();
            assert_eq!(a, back, "serde round-trip failed");
        }
    }

    #[test]
    fn test_gf2k_is_bit() {
        // x^2 = x holds exactly for {0, 1} in every one of these fields.
        for x in [Gf2p16::zero(), Gf2p16::one()] {
            assert!(x.is_bit());
        }
        let mut rng = test_rng();
        let mut nontrivial_checked = 0;
        while nontrivial_checked < 50 {
            let x = Gf2p16::random(&mut rng);
            if x.is_zero() || x == Gf2p16::one() {
                continue;
            }
            assert!(!x.is_bit(), "non-{{0,1}} element {x:?} should not satisfy x^2=x");
            nontrivial_checked += 1;
        }
    }

    /// A worked example of "build your own": a fresh GF(2^5) instantiation with a hand-picked
    /// modulus/generator, verified the same way `Gf2p4`/`Gf2p8`/`Gf2p16` are above. This is
    /// exactly the workflow described in the module docs for adding a `K` not in the curated
    /// list.
    #[test]
    fn test_custom_k_worked_example() {
        // x^5 + x^2 + 1 = 0b100101 = 0x25.
        type Gf2p5 = Gf2k<5, 0x25, 0x02>;
        assert!(verify_field_and_generator::<Gf2p5>());
    }
}
