//! Standalone end-to-end tests of arithmetic-to-binary conversion (blueprint §7.2, tests 7-9).
//!
//! Tier A: `A2BNode` and `B2ANode` are driven directly, with a hand-rolled receiver task per party
//! demuxing `WrappedMessage` exactly as `gf_mul_test.rs` does — no `HoneyBadgerMPCNode` in the
//! loop. `a2b_node_test.rs` covers the same conversions through the node dispatcher.
//!
//! What these tests pin is the arithmetic of the *exact*, full-range conversion:
//!
//! * every value of `F` converts, including the ones that sit on a carry boundary of either of the
//!   adder's two 64-bit additions or on the boundary of the conditional reduction by `p`;
//! * the output is the canonical representative in `[0, p)`, never two's complement;
//! * `b2a_full_width_unchecked ∘ a2b` and `a2b ∘ b2a` are both the identity, the first for every
//!   `x in F` and the second for every bit vector up to `max_width::<F>()`.
//!
//! The conversion preprocessing is dealt honestly by [`utils::a2b_utils`] rather than generated by
//! `PrssDaBitNode`; the reasoning is in that file's header. Nothing here therefore says anything
//! about daBit *generation* — these are tests of the conversion. Generation is covered by
//! `prss_dabit_test.rs` and the `r < p` filter by `edabit_filter_test.rs`.

pub mod utils;

#[path = "utils/a2b_utils.rs"]
mod a2b_utils;

#[path = "utils/conv_width_utils.rs"]
mod conv_width_utils;

use crate::a2b_utils::{
    boundary_values, deal_bits, deal_dabits, deal_edabits, deal_edabits_from, deal_field,
    deal_gf_triples, expected_bits, random_values, recompose_u128, recover_bit, recover_field, F,
    K, P,
};
use crate::conv_width_utils::{
    as_integer, bits_le, fixed_point_corpus, fixed_point_precision, fixed_point_width,
    parallel_offset_adder, serial_a2b_netlist, serial_offset_adder, shift_to_unsigned,
    PARALLEL_AND_BOUND, PARALLEL_DEPTH, SERIAL_AND_BOUND, SERIAL_DEPTH,
};
use crate::utils::test_utils::{fan_in_inboxes, setup_tracing};
use ark_ff::{BigInteger, PrimeField};
use ark_std::rand::rngs::StdRng;
use ark_std::rand::{Rng, SeedableRng};
use std::sync::Arc;
use std::time::Duration;
use stoffelcrypto::common::convert::field_bit_width;
use stoffelcrypto::common::gf2k::share::GfShare;
use stoffelcrypto::common::ProtocolSessionId;
use stoffelcrypto::honeybadger::{
    a2b::a2b::A2BNode,
    b2a::b2a::{max_width, B2ANode},
    binary_circuits::FieldA2BCircuit,
    dabit::{DaBit, EdaBit},
    gf_triple_gen::GfBeaverTriple,
    robust_interpolate::robust_interpolate::RobustShare,
    ProtocolType, SessionId, WrappedMessage,
};
use stoffelmpc_network::fake_network::{
    FakeInnerNetwork, FakeNetwork, FakeNetworkConfig, SenderId,
};
use tokio::task::JoinSet;
use tracing::warn;

/// Generous: these conversions run 7 AND layers plus an arithmetic opening over a `FakeNetwork`
/// shared with every other test in the binary, and a timeout that fires is indistinguishable from
/// a protocol that never completes.
const TIMEOUT: Duration = Duration::from_secs(120);

/// One party's pair of conversion nodes plus the receiver task feeding them.
///
/// `A2BNode` and `B2ANode` are `Clone` over `Arc`-shared stores, so the clone the receiver task
/// owns and the clone a conversion driver owns are the same node.
struct ConvHarness {
    n_parties: usize,
    instance_id: u32,
    network: Vec<Arc<FakeNetwork>>,
    a2b: Vec<A2BNode<F, K>>,
    b2a: Vec<B2ANode<F, K>>,
    /// Held so the receiver tasks outlive the test body: dropping a `JoinSet` aborts its tasks.
    _tasks: JoinSet<()>,
}

impl ConvHarness {
    fn new(n_parties: usize, t: usize, instance_id: u32) -> Self {
        let config = FakeNetworkConfig::new(500);
        let (inner, mut receivers, _) = FakeInnerNetwork::new(n_parties, None, config);
        let network: Vec<Arc<FakeNetwork>> = (0..n_parties)
            .map(|id| Arc::new(FakeNetwork::new(id, inner.clone())))
            .collect();

        let a2b: Vec<A2BNode<F, K>> = (0..n_parties)
            .map(|id| A2BNode::<F, K>::new(id, n_parties, t).unwrap())
            .collect();
        let b2a: Vec<B2ANode<F, K>> = (0..n_parties)
            .map(|id| B2ANode::<F, K>::new(id, n_parties, t).unwrap())
            .collect();

        let mut tasks = JoinSet::new();
        for id in 0..n_parties {
            let mut a2b_node = a2b[id].clone();
            let mut b2a_node = b2a[id].clone();
            let net = network[id].clone();
            let inbox: Vec<(SenderId, tokio::sync::mpsc::Receiver<Vec<u8>>)> =
                std::mem::take(&mut receivers[id])
                    .into_iter()
                    .enumerate()
                    .map(|(sender, rx)| (SenderId::Node(sender), rx))
                    .collect();
            let mut merged = fan_in_inboxes(inbox);

            tasks.spawn(async move {
                while let Some((_sender, bytes)) = merged.recv().await {
                    let wrapped: WrappedMessage = match bincode::deserialize(&bytes) {
                        Ok(wrapped) => wrapped,
                        Err(e) => {
                            warn!(?e, "undeserializable message");
                            continue;
                        }
                    };
                    // Exactly the arms `HoneyBadgerMPCNode::process` routes for these two tags,
                    // each `process` immediately followed by its matching drain (C10): nothing
                    // else moves a finished reconstruction out of the batch-recon store, so a
                    // missing drain is a silent hang rather than an error.
                    match wrapped {
                        WrappedMessage::BatchRecon(msg) => {
                            match msg.session_id.calling_protocol() {
                                Some(ProtocolType::A2B) => {
                                    if let Err(e) =
                                        a2b_node.open.process(msg, Arc::clone(&net)).await
                                    {
                                        warn!(?e, "A2B mask opening");
                                    }
                                    if let Err(e) = a2b_node.drain_open_output().await {
                                        warn!(?e, "A2B mask-opening drain");
                                    }
                                }
                                other => panic!("unexpected BatchRecon caller {other:?}"),
                            }
                        }
                        WrappedMessage::GfBatchRecon(msg) => {
                            match msg.session_id.calling_protocol() {
                                Some(ProtocolType::A2BGfMul) => {
                                    if let Err(e) = a2b_node
                                        .gf_mul
                                        .batch_recon
                                        .process(msg, Arc::clone(&net))
                                        .await
                                    {
                                        warn!(?e, "A2B AND-layer reconstruction");
                                    }
                                    if let Err(e) = a2b_node.drain_gf_mul_output().await {
                                        warn!(?e, "A2B AND-layer drain");
                                    }
                                }
                                Some(ProtocolType::B2A) => {
                                    if let Err(e) =
                                        b2a_node.gf_open.process(msg, Arc::clone(&net)).await
                                    {
                                        warn!(?e, "B2A opening");
                                    }
                                    if let Err(e) = b2a_node.drain_gf_open_output().await {
                                        warn!(?e, "B2A opening drain");
                                    }
                                }
                                other => panic!("unexpected GfBatchRecon caller {other:?}"),
                            }
                        }
                        WrappedMessage::GfMult(msg) => match msg.session_id.calling_protocol() {
                            Some(ProtocolType::A2BGfMul) => {
                                if let Err(e) = a2b_node
                                    .gf_mul
                                    .process(msg.sender, msg.session_id, msg.payload)
                                    .await
                                {
                                    warn!(?e, "A2B AND-layer direct open");
                                }
                            }
                            other => panic!("unexpected GfMult caller {other:?}"),
                        },
                        other => panic!("unexpected wrapped message {other:?}"),
                    }
                }
            });
        }

        Self {
            n_parties,
            instance_id,
            network,
            a2b,
            b2a,
            _tasks: tasks,
        }
    }

    fn a2b_session(&self, exec: u64) -> SessionId {
        SessionId::new(
            ProtocolType::A2B,
            SessionId::pack_slot(exec, 0, 0),
            self.instance_id,
        )
    }

    fn b2a_session(&self, exec: u64) -> SessionId {
        SessionId::new(
            ProtocolType::B2A,
            SessionId::pack_slot(exec, 0, 0),
            self.instance_id,
        )
    }

    /// Runs one A2B batch on every party and returns the bit shares, indexed
    /// `[party][value][bit]`.
    async fn a2b(
        &self,
        exec: u64,
        inputs: Vec<Vec<RobustShare<F>>>,
        edabits: Vec<Vec<EdaBit<F, K>>>,
        triples: Vec<Vec<GfBeaverTriple<K>>>,
    ) -> Vec<Vec<Vec<GfShare<K>>>> {
        let session_id = self.a2b_session(exec);
        let mut handles = Vec::with_capacity(self.n_parties);
        for party in 0..self.n_parties {
            let mut node = self.a2b[party].clone();
            let net = self.network[party].clone();
            let x = inputs[party].clone();
            let edabits = edabits[party].clone();
            let triples = triples[party].clone();
            handles.push(tokio::spawn(async move {
                node.init(session_id, x, edabits, triples, TIMEOUT, net)
                    .await
                    .unwrap_or_else(|e| panic!("A2B init failed on party {party}: {e:?}"));
                let bits = node
                    .wait_for_result(session_id, TIMEOUT)
                    .await
                    .unwrap_or_else(|e| panic!("A2B result missing on party {party}: {e:?}"));
                assert!(
                    node.clear_store(session_id).await,
                    "A2B session was not retired on party {party}"
                );
                bits
            }));
        }

        let mut results = Vec::with_capacity(self.n_parties);
        for handle in handles {
            results.push(handle.await.expect("A2B task panicked"));
        }
        results
    }

    /// Runs one B2A batch on every party and returns the arithmetic shares, indexed
    /// `[party][value]`. `full_width` selects `b2a_full_width_unchecked` over `b2a`.
    async fn b2a(
        &self,
        exec: u64,
        bits: Vec<Vec<Vec<GfShare<K>>>>,
        dabits: Vec<Vec<DaBit<F, K>>>,
        full_width: bool,
    ) -> Vec<Vec<RobustShare<F>>> {
        let session_id = self.b2a_session(exec);
        let mut handles = Vec::with_capacity(self.n_parties);
        for party in 0..self.n_parties {
            let mut node = self.b2a[party].clone();
            let net = self.network[party].clone();
            let bits = bits[party].clone();
            let dabits = dabits[party].clone();
            handles.push(tokio::spawn(async move {
                let started = if full_width {
                    node.b2a_full_width_unchecked(session_id, bits, dabits, TIMEOUT, net)
                        .await
                } else {
                    node.b2a(session_id, bits, dabits, TIMEOUT, net).await
                };
                started.unwrap_or_else(|e| panic!("B2A init failed on party {party}: {e:?}"));
                let values = node
                    .wait_for_result(session_id, TIMEOUT)
                    .await
                    .unwrap_or_else(|e| panic!("B2A result missing on party {party}: {e:?}"));
                assert!(
                    node.clear_store(session_id).await,
                    "B2A session was not retired on party {party}"
                );
                values
            }));
        }

        let mut results = Vec::with_capacity(self.n_parties);
        for handle in handles {
            results.push(handle.await.expect("B2A task panicked"));
        }
        results
    }
}

/// Checks one A2B batch's output against the canonical bit decomposition of every input.
///
/// Asserts three separate things, because two of them can hold while the third fails: that every
/// bit share is well formed (degree `t`, this party's index), that each bit reconstructs to the
/// right bit from a *quorum*, and that the recomposition of the whole 64-bit vector is the input
/// as an integer — the last is what catches a decomposition that is right bit by bit against a
/// wrong expectation.
fn assert_a2b_matches(
    label: &str,
    values: &[F],
    results: &[Vec<Vec<GfShare<K>>>],
    n_parties: usize,
    t: usize,
) {
    let width = field_bit_width::<F>();
    for (party, per_value) in results.iter().enumerate() {
        assert_eq!(
            per_value.len(),
            values.len(),
            "{label}: party {party} returned the wrong number of conversions"
        );
        for bits in per_value {
            assert_eq!(bits.len(), width, "{label}: wrong output width");
            for bit in bits {
                assert_eq!(bit.degree, t, "{label}: output share is not degree t");
                assert_eq!(
                    bit.id, party,
                    "{label}: output share carries a foreign index"
                );
            }
        }
    }

    for (index, value) in values.iter().enumerate() {
        let want = expected_bits(*value);
        let mut got = Vec::with_capacity(width);
        for bit in 0..width {
            let column: Vec<GfShare<K>> = results
                .iter()
                .map(|per_value| per_value[index][bit].clone())
                .collect();
            got.push(recover_bit(&column, n_parties, t));
        }
        assert_eq!(
            got, want,
            "{label}: bit decomposition of value {index} is wrong"
        );

        let mut repr = [0u8; 8];
        repr.copy_from_slice(&value.into_bigint().to_bytes_le()[0..8]);
        assert_eq!(
            recompose_u128(&got),
            u64::from_le_bytes(repr) as u128,
            "{label}: recomposition of value {index} is not the canonical representative"
        );
    }
}

/// Drives one A2B batch end to end from plain field values, dealing everything it needs.
async fn a2b_case(
    label: &str,
    n_parties: usize,
    t: usize,
    instance_id: u32,
    values: &[F],
    seed: u64,
) {
    setup_tracing();
    let harness = ConvHarness::new(n_parties, t, instance_id);
    let mut rng = StdRng::seed_from_u64(seed);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, values, &mut rng);
    let edabits = deal_edabits(n_parties, t, values.len(), &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);

    let results = harness.a2b(1, inputs, edabits, triples).await;
    assert_a2b_matches(label, values, &results, n_parties, t);
}

// -------------------------------------------------------------------------------------------
// Full-range correctness
// -------------------------------------------------------------------------------------------

/// Every value on a boundary of the exact conversion, in one batch.
///
/// Twelve conversions at `t = 3` is an exact multiple of the `t + 1` batch-reconstruction width,
/// so the mask opening needs no padding — one of the three shapes the chunking splits on.
#[tokio::test]
async fn a2b_e2e_boundary_values() {
    let corpus = boundary_values();
    let values: Vec<F> = corpus.iter().map(|(_, value)| *value).collect();
    assert_eq!(
        values.len() % 4,
        0,
        "this test wants an exact chunk multiple"
    );
    a2b_case("boundary", 10, 3, 201, &values, 2_001).await;
}

/// A batch whose size leaves a remainder against the `t + 1` reconstruction width, so the mask
/// opening is padded — the second chunking shape.
#[tokio::test]
async fn a2b_e2e_random_batch_with_remainder() {
    let mut rng = StdRng::seed_from_u64(2_002);
    let values = random_values(7, &mut rng);
    assert_eq!(values.len() % 4, 3);
    a2b_case("random-remainder", 10, 3, 202, &values, 2_003).await;
}

/// A batch smaller than the reconstruction width — the third chunking shape, and the one where a
/// padding bug would show up as a decode failure rather than a wrong value.
#[tokio::test]
async fn a2b_e2e_batch_below_chunk_width() {
    let values = vec![F::from(1u64 << 32), F::from(P - (1u64 << 32))];
    assert!(values.len() < 4);
    a2b_case("below-chunk", 10, 3, 203, &values, 2_004).await;
}

/// The same corpus at the smallest admissible configuration, `n = 3t + 1 = 4`.
#[tokio::test]
async fn a2b_e2e_boundary_values_at_n4() {
    let corpus = boundary_values();
    let values: Vec<F> = corpus.iter().map(|(_, value)| *value).collect();
    a2b_case("boundary-n4", 4, 1, 204, &values, 2_005).await;
}

/// A2B returns the bits of the canonical representative in `[0, p)`, **not** two's complement.
///
/// `mpc/src/common/types` encodes `-|v|` as `p - |v|`, so `-1` is `p - 1 = 0xFFFF_FFFF_0000_0000`
/// and its bits 0..32 are all clear. A caller that wants a sign bit shifts by `2^(k-1)` first,
/// exactly as `truncpr` does; a caller that assumes two's complement reads `-1` as a 33-bit
/// positive number's complement and gets nonsense. Pins blueprint §2.7.
#[tokio::test]
async fn a2b_signed_is_canonical_not_twos_complement() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let minus_one = F::from(0u64) - F::from(1u64);
    let harness = ConvHarness::new(n_parties, t, 205);
    let mut rng = StdRng::seed_from_u64(2_006);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &[minus_one], &mut rng);
    let edabits = deal_edabits(n_parties, t, 1, &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion, &mut rng);

    let results = harness.a2b(1, inputs, edabits, triples).await;

    let width = field_bit_width::<F>();
    let mut got = Vec::with_capacity(width);
    for bit in 0..width {
        let column: Vec<GfShare<K>> = results.iter().map(|r| r[0][bit].clone()).collect();
        got.push(recover_bit(&column, n_parties, t));
    }

    assert_eq!(
        recompose_u128(&got),
        0xFFFF_FFFF_0000_0000u128,
        "-1 must decompose as p - 1"
    );
    assert!(
        got[0..32].iter().all(|bit| !bit),
        "two's complement would set every low bit of -1; the canonical representative clears them"
    );
    assert!(
        got[32..64].iter().all(|bit| *bit),
        "p - 1 has every bit from 32 up set"
    );
}

// -------------------------------------------------------------------------------------------
// Round trips
// -------------------------------------------------------------------------------------------

/// `b2a_full_width_unchecked(a2b([x])) == [x]` for every `x in F`.
///
/// This is the one caller that can discharge `b2a_full_width_unchecked`'s precondition: A2B emits
/// the bits of the canonical representative, which is by definition below `p`, so the 64-bit
/// recomposition is faithful. Any other 64-bit caller silently gets `x mod p` for the `2^32 - 1`
/// payloads in `[p, 2^64)`, which is exactly why the unchecked entry point is named as it is.
#[tokio::test]
async fn a2b_then_b2a_full_width_round_trips() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let width = field_bit_width::<F>();
    // Includes `p - 1`, whose 64-bit recomposition is one below the modulus: the exact case that
    // makes the full-width variant unsafe for any *other* caller.
    let values = vec![
        F::from(0u64),
        F::from(1u64),
        F::from(1u64 << 32),
        F::from(1u64 << 63),
        F::from(0u64) - F::from(1u64),
    ];

    let harness = ConvHarness::new(n_parties, t, 206);
    let mut rng = StdRng::seed_from_u64(2_007);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &values, &mut rng);
    let edabits = deal_edabits(n_parties, t, values.len(), &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);
    let dabits = deal_dabits(n_parties, t, width * values.len(), &mut rng);

    let bits = harness.a2b(1, inputs, edabits, triples).await;
    assert_a2b_matches("roundtrip-forward", &values, &bits, n_parties, t);

    let back = harness.b2a(1, bits, dabits, true).await;
    for (index, want) in values.iter().enumerate() {
        let column: Vec<RobustShare<F>> = back
            .iter()
            .map(|per_value| per_value[index].clone())
            .collect();
        assert_eq!(
            recover_field(&column, n_parties, t),
            *want,
            "round trip lost value {index}"
        );
    }
}

/// `a2b(b2a(bits)) == bits` for random bit vectors at the B2A width bound.
///
/// The other direction of the round trip, and the one that pins the *widths* against each other:
/// B2A accepts at most `max_width::<F>() = 63` bits while A2B always emits 64, so the identity
/// holds only if A2B's extra top bit is zero — which it is, because `sum_{i<63} 2^i b_i < 2^63 < p`
/// cannot reach bit 63 of the canonical representative.
#[tokio::test]
async fn b2a_then_a2b_round_trips() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let ell = max_width::<F>();
    assert_eq!(ell, 63);
    let values = 3usize;

    let harness = ConvHarness::new(n_parties, t, 207);
    let mut rng = StdRng::seed_from_u64(2_008);

    // Two random vectors and one all-ones vector: `2^63 - 1` is the largest value B2A can carry,
    // and the one a width-by-one overshoot gets wrong.
    let clear: Vec<Vec<bool>> = (0..values)
        .map(|index| {
            (0..ell)
                .map(|_| if index == values - 1 { true } else { rng.gen() })
                .collect()
        })
        .collect();

    let mut per_party_bits: Vec<Vec<Vec<GfShare<K>>>> = vec![Vec::new(); n_parties];
    for value_bits in &clear {
        let columns = deal_bits(n_parties, t, value_bits, &mut rng);
        for party in 0..n_parties {
            per_party_bits[party].push(columns[party].clone());
        }
    }

    let dabits = deal_dabits(n_parties, t, ell * values, &mut rng);
    let arithmetic = harness.b2a(1, per_party_bits, dabits, false).await;

    let mut recovered = Vec::with_capacity(values);
    for index in 0..values {
        let column: Vec<RobustShare<F>> = arithmetic
            .iter()
            .map(|per_value| per_value[index].clone())
            .collect();
        let value = recover_field(&column, n_parties, t);
        assert_eq!(
            value,
            F::from(recompose_u128(&clear[index]) as u64),
            "B2A recomposed value {index} wrongly"
        );
        recovered.push(value);
    }

    // Feed the arithmetic shares B2A produced straight back in, without re-dealing them.
    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let edabits = deal_edabits(n_parties, t, values, &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values, &mut rng);
    let inputs: Vec<Vec<RobustShare<F>>> = arithmetic;

    let bits = harness.a2b(2, inputs, edabits, triples).await;
    assert_a2b_matches("roundtrip-reverse", &recovered, &bits, n_parties, t);

    for (index, want) in clear.iter().enumerate() {
        for bit in 0..ell {
            let column: Vec<GfShare<K>> = bits.iter().map(|r| r[index][bit].clone()).collect();
            assert_eq!(
                recover_bit(&column, n_parties, t),
                want[bit],
                "value {index} bit {bit} did not survive the round trip"
            );
        }
        let top: Vec<GfShare<K>> = bits.iter().map(|r| r[index][ell].clone()).collect();
        assert!(
            !recover_bit(&top, n_parties, t),
            "a value below 2^63 must leave A2B's top bit clear"
        );
    }
}

// -------------------------------------------------------------------------------------------
// Preconditions of the full-range path
// -------------------------------------------------------------------------------------------

/// A short edaBit is refused, not silently zero-extended.
///
/// A2B masks the whole canonical range, so an edaBit narrower than the field width cannot mask it;
/// a short one is also, by construction, one the `r < p` filter was never applied to, and with
/// `r >= p` the adder's "at most one subtraction of `p`" argument fails and the output is simply
/// wrong. The refusal happens before any message is sent.
#[tokio::test]
async fn a2b_refuses_a_short_edabit() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let harness = ConvHarness::new(n_parties, t, 208);
    let mut rng = StdRng::seed_from_u64(2_009);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &[F::from(7u64)], &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion, &mut rng);
    // `compose` rather than `compose_full_width`: a narrow edaBit, which is the only kind that can
    // be built without an opened overflow bit.
    let narrow = deal_dabits(n_parties, t, max_width::<F>(), &mut rng);

    let mut node = harness.a2b[0].clone();
    let edabit = EdaBit::compose(&narrow[0], max_width::<F>()).unwrap();
    let err = node
        .init(
            harness.a2b_session(1),
            inputs[0].clone(),
            vec![edabit],
            triples[0].clone(),
            TIMEOUT,
            harness.network[0].clone(),
        )
        .await
        .expect_err("a short edabit must be refused");
    assert!(
        format!("{err:?}").contains("EdaBitWidthMismatch"),
        "unexpected error: {err:?}"
    );
}

/// Every branch of the conditional reduction, driven by a **chosen** mask rather than a sampled
/// one.
///
/// With `y = (x - r) mod p`, `A = y + r` over the integers and `d = 2^64 - p = 2^32 - 1`, the
/// parallel offset adder's single carry is determined by `x` and `r` alone. `c2` is the carry out
/// of `(y + d) + r`, and `c2 = 1` iff `A >= p`:
///
/// | case | `A` | `c2` | selected | first adder wraps |
/// |---|---|---|---|---|
/// | `x >= r` | `x < p` | 0 | `t1 = A = x` | no |
/// | `x < r`, `x < 2^32 - 1` | `x + p < 2^64` | 1 | `t2 = A - p = x` | no |
/// | `x < r`, `x >= 2^32 - 1` | `x + p >= 2^64` | 1 | `t2 = A - p = x` | **yes** |
///
/// The last column is what used to be the serial chain's `c1`. That carry is no longer formed —
/// `Builder::finish` deletes its whole cone — but the row is still the interesting one, because it
/// is exactly where `t1` is the wrapped, meaningless `A - 2^64` and the multiplexer must not pick
/// it. Sampling `r` at random reaches the three rows with probability roughly `1/2`, `1/2` and
/// `2^-32`, so the last is pinned here explicitly rather than left to luck.
#[tokio::test]
async fn a2b_covers_every_carry_branch() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    // (value, mask, which row of the table above)
    let cases: Vec<(u64, u64, &str)> = vec![
        (1u64 << 40, 1, "x >= r, no reduction"),
        (P - 1, P - 1, "x == r, y == 0"),
        (5, P - 1, "x < r, x < 2^32 - 1: c1 = 0, c2 = 1"),
        (
            (1u64 << 32) - 2,
            P - 1,
            "x < r, one below the c1 boundary: c1 = 0, c2 = 1",
        ),
        (
            (1u64 << 32) - 1,
            P - 1,
            "x < r, exactly at the c1 boundary: c1 = 1, c2 = 0",
        ),
        (1u64 << 40, P - 1, "x < r, x >= 2^32 - 1: c1 = 1, c2 = 0"),
        (P - 2, P - 1, "x < r, largest possible x: c1 = 1, c2 = 0"),
    ];

    let values: Vec<F> = cases.iter().map(|(x, _, _)| F::from(*x)).collect();
    let masks: Vec<u64> = cases.iter().map(|(_, r, _)| *r).collect();

    let harness = ConvHarness::new(n_parties, t, 209);
    let mut rng = StdRng::seed_from_u64(2_010);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &values, &mut rng);
    let edabits = deal_edabits_from(n_parties, t, &masks, &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);

    let results = harness.a2b(1, inputs, edabits, triples).await;
    assert_a2b_matches("carry-branches", &values, &results, n_parties, t);
}

/// A broad random sweep, so that a bug confined to some unremarkable bit pattern is not missed by
/// a corpus made entirely of special cases.
#[tokio::test]
async fn a2b_e2e_random_sweep() {
    let mut rng = StdRng::seed_from_u64(2_011);
    let values = random_values(24, &mut rng);
    a2b_case("random-sweep", 4, 1, 210, &values, 2_012).await;
}

// -------------------------------------------------------------------------------------------
// The fixed-point width, `ell = 33`
// -------------------------------------------------------------------------------------------

/// A2B at the fixed-point width leaves bits `33..64` clear, for every payload the width admits.
///
/// `FixedPointPrecision::new(32, 16)` is this repo's default, and the plan's §2.4 attaches
/// `ell = k + 1 = 33` to it: `truncpr` already shifts a signed `k`-bit value into `[0, 2^k]`, a
/// closed interval whose upper endpoint needs the 33rd bit, and an unrescaled sum of two shifted
/// operands sets that bit outright.
///
/// The assertion is stronger than "the low 33 bits are right". A2B always emits 64 bits, so a
/// caller narrowing to 33 is relying on the high 31 being clear — and a conversion that got the
/// payload right while leaving rubbish above it would pass a low-bits-only check and then lose the
/// value the moment anyone fed it to B2A. Both halves are checked here.
#[tokio::test]
async fn a2b_at_the_fixed_point_width_leaves_the_high_bits_clear() {
    setup_tracing();

    let (n_parties, t) = (10usize, 3usize);
    let precision = fixed_point_precision();
    let ell = fixed_point_width();
    assert_eq!((precision.k(), precision.f()), (32, 16), "the repo default");
    assert_eq!(ell, 33, "ell = k + 1 at the default precision");

    let corpus = fixed_point_corpus();
    let values: Vec<F> = corpus.iter().map(|(_, v)| F::from(*v)).collect();

    let harness = ConvHarness::new(n_parties, t, 211);
    let mut rng = StdRng::seed_from_u64(2_013);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &values, &mut rng);
    let edabits = deal_edabits(n_parties, t, values.len(), &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);

    let results = harness.a2b(1, inputs, edabits, triples).await;
    assert_a2b_matches("fixed-point-width", &values, &results, n_parties, t);

    let width = field_bit_width::<F>();
    for (index, (label, payload)) in corpus.iter().enumerate() {
        let got: Vec<bool> = (0..width)
            .map(|bit| {
                let column: Vec<GfShare<K>> =
                    results.iter().map(|r| r[index][bit].clone()).collect();
                recover_bit(&column, n_parties, t)
            })
            .collect();
        assert!(
            got[ell..].iter().all(|bit| !bit),
            "{label}: a payload below 2^{ell} must leave every bit from {ell} up clear"
        );
        assert_eq!(
            as_integer(&got[0..ell]),
            *payload as u128,
            "{label}: the low {ell} bits are not the payload"
        );
    }
}

/// The standing negative result of plan §2.4, made concrete: an **unshifted** negative
/// fixed-point value is not 33 bits wide, and no amount of narrowing makes it so.
///
/// `mpc/src/common/types` encodes `-v` as `p - v`, so `-1` is `0xFFFF_FFFF_0000_0000` — a 64-bit
/// number whose low 32 bits are clear. Narrowing A2B's output to the fixed-point width would
/// silently read it as zero. The free `+2^(k-1)` shift that `truncpr.rs:192` already applies is
/// what makes the value narrow, and this test pins both halves of that: the unshifted form
/// overflows the width, the shifted form does not.
///
/// It also pins the *cost* half of the same negative result. A2B's preprocessing does not shrink
/// at `ell = 33`: the mask has to be uniform on `[0, p)` whatever the payload's width, so the
/// edaBit stays 64 daBits and the triple bound stays the full-width one. The blueprint's cost
/// tables quoted "ell = 33 is cheaper"; §2.4 corrects that to "identical preprocessing, only the
/// circuit narrows, and only against a certified bit width".
#[tokio::test]
async fn a2b_does_not_narrow_an_unshifted_negative_fixed_point_value() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let ell = fixed_point_width();
    let width = field_bit_width::<F>();

    // `-1` unshifted, and `-1` shifted: `2^31 - 1`.
    let minus_one = F::from(0u64) - F::from(1u64);
    let shifted = F::from(shift_to_unsigned(-1));
    let values = vec![minus_one, shifted];

    let harness = ConvHarness::new(n_parties, t, 212);
    let mut rng = StdRng::seed_from_u64(2_014);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &values, &mut rng);
    let edabits = deal_edabits(n_parties, t, values.len(), &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);

    // The preprocessing is full width on both, and is drawn before either value is known: there
    // is no `ell` parameter anywhere on this path, which is the cost half of §2.4.
    assert_eq!(
        per_conversion, PARALLEL_AND_BOUND,
        "the triple bound is the full-width one regardless of the payload width"
    );
    for party_edabits in &edabits {
        assert_eq!(
            party_edabits[0].bits.len(),
            width,
            "the mask stays 64 daBits wide at ell = 33"
        );
    }

    let results = harness.a2b(1, inputs, edabits, triples).await;
    assert_a2b_matches("unshifted-negative", &values, &results, n_parties, t);

    let recover_all = |index: usize| -> Vec<bool> {
        (0..width)
            .map(|bit| {
                let column: Vec<GfShare<K>> =
                    results.iter().map(|r| r[index][bit].clone()).collect();
                recover_bit(&column, n_parties, t)
            })
            .collect()
    };

    let unshifted = recover_all(0);
    assert!(
        unshifted[ell..].iter().any(|bit| *bit),
        "p - 1 must overflow the fixed-point width"
    );
    // And what narrowing it *would* produce is the sharper half of the hazard: not an obviously
    // broken value, but `2^32` — the headroom bit alone. Read back as a shifted fixed-point
    // number that is `2^32 - 2^31 = +2^31`, one past the largest representable positive. So `-1`
    // narrows to the extreme *opposite* end of the range, with nothing anywhere to object.
    assert_eq!(
        as_integer(&unshifted[0..ell]),
        1u128 << 32,
        "p - 1 narrows to the headroom bit alone"
    );
    assert_ne!(
        as_integer(&unshifted[0..ell]),
        shift_to_unsigned(-1) as u128,
        "the narrowed unshifted form must not coincidentally be the shifted one"
    );

    let after_shift = recover_all(1);
    assert!(
        after_shift[ell..].iter().all(|bit| !bit),
        "the shifted form fits the width"
    );
    assert_eq!(
        as_integer(&after_shift[0..ell]),
        shift_to_unsigned(-1) as u128,
        "the shifted form narrows to 2^31 - 1"
    );
}

/// `b2a(narrow_to_33(a2b([x]))) == [x]` over the whole fixed-point corpus.
///
/// The round trip a fixed-point mixed circuit actually performs: decompose, operate on 33 bits,
/// recompose. It is exact because of the test above — A2B leaves bits `33..64` clear for every
/// in-range payload — and `ell = 33` is comfortably inside B2A's `max_width::<F>() = 63` bound, so
/// it takes the checked entry point rather than the full-width one.
///
/// B2A's cost *does* fall linearly with `ell` (§2.4), and that is pinned by construction: the
/// conversion is handed exactly `33 * values` daBits and `B2ANode::b2a` rejects any other count
/// outright, so completing at all is the assertion.
#[tokio::test]
async fn a2b_then_b2a_round_trips_at_the_fixed_point_width() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let ell = fixed_point_width();
    let corpus = fixed_point_corpus();
    let values: Vec<F> = corpus.iter().map(|(_, v)| F::from(*v)).collect();

    let harness = ConvHarness::new(n_parties, t, 213);
    let mut rng = StdRng::seed_from_u64(2_015);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &values, &mut rng);
    let edabits = deal_edabits(n_parties, t, values.len(), &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);
    let dabits = deal_dabits(n_parties, t, ell * values.len(), &mut rng);

    let bits = harness.a2b(1, inputs, edabits, triples).await;
    assert_a2b_matches("fixed-point-roundtrip", &values, &bits, n_parties, t);

    let narrowed: Vec<Vec<Vec<GfShare<K>>>> = bits
        .iter()
        .map(|per_value| {
            per_value
                .iter()
                .map(|value_bits| value_bits[0..ell].to_vec())
                .collect()
        })
        .collect();

    let back = harness.b2a(1, narrowed, dabits, false).await;
    for (index, (label, payload)) in corpus.iter().enumerate() {
        let column: Vec<RobustShare<F>> = back.iter().map(|per| per[index].clone()).collect();
        assert_eq!(
            recover_field(&column, n_parties, t),
            F::from(*payload),
            "{label}: the fixed-point round trip lost the value"
        );
    }
}

// -------------------------------------------------------------------------------------------
// The depth-7 circuit against the depth-13 one it replaces
// -------------------------------------------------------------------------------------------

/// The parallel offset adder computes exactly the function the serial chain did, on every input
/// that matters.
///
/// The two circuits differ in more than their layering. The serial chain reduces on `c1 XOR c2`,
/// where `c1` is the carry out of `y + r` and `c2` the carry out of adding `d` to the *truncated*
/// sum; the parallel form never forms `c1` and reduces on `c2` alone, where that `c2` is the carry
/// out of a different addition, `(y + d) + r`. That the two agree is a theorem about `p`, not an
/// algebraic identity, so it is worth a sweep rather than an argument.
///
/// The sweep is exhaustive over the cross product of the boundary corpus with itself — every
/// `(x, r)` pair on a carry boundary of either form, including the `2^32 - 1` neighbourhood where
/// the serial chain's `c1` is the deciding bit — plus a uniform tail. Both models are checked
/// against `(y + r) mod p` as well as against each other, so a shared misreading of the algebra
/// cannot pass.
#[test]
fn the_parallel_offset_adder_agrees_with_the_serial_chain_it_replaced() {
    let mut corpus: Vec<u64> = boundary_values()
        .iter()
        .map(|(_, value)| {
            let mut repr = [0u8; 8];
            repr.copy_from_slice(&value.into_bigint().to_bytes_le()[0..8]);
            u64::from_le_bytes(repr)
        })
        .collect();
    // The `2^32 - 1` neighbourhood again, from the mask's side this time, plus the extremes of
    // the admissible range for `r`.
    corpus.extend_from_slice(&[(1u64 << 32) - 2, (1u64 << 32) - 1, 1u64 << 32, P - 1, P / 2]);

    let mut rng = StdRng::seed_from_u64(2_016);
    let mut extra: Vec<u64> = Vec::with_capacity(64);
    while extra.len() < 64 {
        let candidate: u64 = rng.gen();
        if candidate < P {
            extra.push(candidate);
        }
    }
    corpus.extend_from_slice(&extra);

    let mut checked = 0usize;
    for &x in &corpus {
        assert!(x < P, "the corpus must be canonical");
        for &r in &corpus {
            // `y = (x - r) mod p`, exactly what the mask opening publishes. Written as
            // `p - (r - x)` rather than `x + p - r`: both are the same residue, but the latter
            // overflows `u64` for a large `x`.
            let y = if x >= r { x - r } else { P - (r - x) };
            let serial = serial_offset_adder(y, r);
            let parallel = parallel_offset_adder(y, r);
            assert_eq!(
                serial, parallel,
                "the two circuits disagree at y = {y}, r = {r}"
            );
            assert_eq!(
                parallel, x,
                "the conversion is not the identity at y = {y}, r = {r}"
            );
            checked += 1;
        }
    }
    assert!(checked > 6_000, "the sweep collapsed to {checked} pairs");
}

/// The **protocol's** output is the serial chain's output, on masks chosen to pin each branch.
///
/// The sweep above compares two clear-text models. This compares the model that describes the
/// replaced circuit against what the deployed one actually returns over the wire — the assertion
/// that closes the loop, since a model can agree with a theorem and still fail to describe the
/// code. Masks are chosen rather than sampled, because the row where the serial chain's `c1` is
/// set has probability `2^-32` under a uniform mask.
#[tokio::test]
async fn a2b_output_matches_the_serial_chain_on_chosen_masks() {
    setup_tracing();

    let (n_parties, t) = (4usize, 1usize);
    let width = field_bit_width::<F>();

    // (x, r), one per row of the branch table in `a2b_covers_every_carry_branch`, plus the
    // degenerate `r = 0` and `x = r` cases.
    let cases: Vec<(u64, u64)> = vec![
        (1u64 << 40, 0),
        (1u64 << 40, 1),
        (P - 1, P - 1),
        (5, P - 1),
        ((1u64 << 32) - 2, P - 1),
        ((1u64 << 32) - 1, P - 1),
        (P - 2, P - 1),
        (0, 1),
        (0xDEAD_BEEF_CAFE_F00D % P, 0x0123_4567_89AB_CDEF),
    ];

    let values: Vec<F> = cases.iter().map(|(x, _)| F::from(*x)).collect();
    let masks: Vec<u64> = cases.iter().map(|(_, r)| *r).collect();

    let harness = ConvHarness::new(n_parties, t, 214);
    let mut rng = StdRng::seed_from_u64(2_017);

    let per_conversion = A2BNode::<F, K>::gf_triples_per_conversion().unwrap();
    let inputs = deal_field(n_parties, t, &values, &mut rng);
    let edabits = deal_edabits_from(n_parties, t, &masks, &mut rng);
    let triples = deal_gf_triples(n_parties, t, per_conversion * values.len(), &mut rng);

    let results = harness.a2b(1, inputs, edabits, triples).await;

    for (index, (x, r)) in cases.iter().enumerate() {
        let y = if x >= r { x - r } else { P - (r - x) };
        let want = bits_le(serial_offset_adder(y, *r), width);
        let got: Vec<bool> = (0..width)
            .map(|bit| {
                let column: Vec<GfShare<K>> =
                    results.iter().map(|res| res[index][bit].clone()).collect();
                recover_bit(&column, n_parties, t)
            })
            .collect();
        assert_eq!(
            got, want,
            "the protocol and the replaced serial chain disagree at x = {x}, r = {r}"
        );
        // And the serial chain was itself right, so this is not two wrongs agreeing.
        assert_eq!(
            as_integer(&want),
            *x as u128,
            "serial model wrong at x = {x}"
        );
    }
}

/// The replacement's headline trade, pinned as a pair of netlists rather than as a comment:
/// **+11% ANDs on the sizing bound for -46% depth**.
///
/// Both netlists are built from the same public `Builder` and prefix primitives, so this is a
/// like-for-like comparison after the same constant folding and backward-liveness pass. The serial
/// chain's bound is a *realisable* plan — an all-ones `y` is admissible there — while the parallel
/// one's is analytic, because an all-ones `y` would make `Y = y + d` wrap and
/// `FieldA2BCircuit::new` rejects it. That asymmetry is the reason the two numbers are quoted from
/// different kinds of witness, and it is why `max_and_count()` is a bound rather than a maximum:
/// the largest count an admissible `y` reaches is 693, not 695.
///
/// Message rounds follow from the depth: `2 + layers * rounds_per_opening`, the leading 2 being
/// the mask opening's own `BatchRecon` round trip. So 13 layers was 28 batched rounds and 7 is
/// 16. `OpeningPolicy::Direct` governs the AND layers only — the mask opening stays batched — so
/// the same 7 layers is **9**, not the plan's 8.
#[test]
fn the_parallel_circuit_is_depth_7_where_the_serial_chain_was_13() {
    let width = field_bit_width::<F>();
    assert_eq!(width, 64);

    let serial = serial_a2b_netlist(width);
    assert_eq!(
        (serial.and_count(), serial.layers()),
        (SERIAL_AND_BOUND, SERIAL_DEPTH),
        "the replaced serial chain is 626 ANDs at depth 13"
    );

    let parallel_ands = FieldA2BCircuit::<F>::max_and_count().unwrap();
    let parallel_depth = FieldA2BCircuit::<F>::max_layers().unwrap();
    assert_eq!(
        (parallel_ands, parallel_depth),
        (PARALLEL_AND_BOUND, PARALLEL_DEPTH),
        "the landed parallel offset adder is 695 ANDs at depth 7"
    );

    // The trade, in the direction the plan claims it: dearer per conversion, shallower.
    assert!(parallel_ands > SERIAL_AND_BOUND);
    assert!(parallel_depth < SERIAL_DEPTH);
    assert_eq!(
        A2BNode::<F, K>::gf_triples_per_conversion().unwrap(),
        parallel_ands,
        "the preprocessing sizer must be handed the bound, not the average"
    );
    assert_eq!(
        A2BNode::<F, K>::max_and_layers().unwrap(),
        parallel_depth,
        "the wave count must be the circuit's depth"
    );
}
