// Allow style lints that don't affect correctness - to be fixed incrementally
#![allow(clippy::int_plus_one)]
#![allow(clippy::redundant_field_names)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::useless_vec)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::ptr_arg)]
#![allow(clippy::empty_line_after_doc_comments)]
#![allow(clippy::module_inception)]
#![allow(clippy::doc_overindented_list_items)]
#![allow(clippy::manual_div_ceil)]
#![allow(clippy::manual_is_multiple_of)]
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_late_init)]
#![allow(clippy::needless_range_loop)]
#![allow(clippy::manual_unwrap_or_default)]
#![allow(clippy::collapsible_else_if)]
#![allow(clippy::collapsible_if)]
#![allow(clippy::single_match)]
#![allow(clippy::match_like_matches_macro)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::result_unit_err)]
#![allow(clippy::comparison_chain)]
#![allow(clippy::manual_map)]
#![allow(clippy::uninlined_format_args)]
#![allow(clippy::nonminimal_bool)]
#![allow(clippy::let_unit_value)]
#![allow(clippy::redundant_closure)]
#![allow(clippy::needless_borrow)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::unnecessary_lazy_evaluations)]
#![allow(clippy::manual_repeat_n)]
#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_borrows_for_generic_args)]
#![allow(clippy::should_implement_trait)]
#![allow(clippy::field_reassign_with_default)]
#![allow(clippy::map_entry)]
#![allow(clippy::or_fun_call)]
#![allow(clippy::iter_nth_zero)]
#![allow(clippy::blocks_in_conditions)]
#![allow(clippy::only_used_in_recursion)]
#![allow(clippy::from_over_into)]
#![allow(clippy::manual_async_fn)]
#![allow(clippy::single_char_pattern)]
#![allow(clippy::assign_op_pattern)]
#![allow(clippy::option_map_unit_fn)]
#![allow(clippy::manual_clamp)]
#![allow(clippy::needless_return)]
#![allow(clippy::len_zero)]
#![allow(clippy::unwrap_or_default)]
#![allow(clippy::get_first)]
#![allow(clippy::manual_contains)]
#![allow(clippy::unused_enumerate_index)]
#![allow(clippy::legacy_numeric_constants)]
#![allow(clippy::not_unsafe_ptr_arg_deref)]
#![allow(clippy::useless_conversion)]
#![allow(clippy::iter_kv_map)]
#![allow(clippy::op_ref)]
#![allow(clippy::let_and_return)]
#![allow(clippy::borrow_deref_ref)]
#![allow(clippy::bind_instead_of_map)]
#![allow(clippy::unnecessary_cast)]

pub mod adkg;
pub mod common;
pub mod ffi;
/// This module implements the HoneyBadger protocol presented in the paper
/// ["HoneyBadgerMPC and AsynchroMix: Practical AsynchronousMPC and its Application to Anonymous Communication"][honeybadger-paper].
///
/// [honeybadger-paper]: https://eprint.iacr.org/2019/883.pdf
pub mod honeybadger;
